use crate::keycodes::VK;

pub fn raw_keycode_to_vk(code: u16) -> VK {
    match code {
        0 => VK::MouseLeft, // Left mouse button
        1 => VK::MouseRight, // Right mouse button
        2 => VK::MouseMiddle, // Middle mouse button (three-button mouse)
        // TODO: TEST REQUIRED FOR TWO ITEMS BELOW
        // => VK::MouseX1, // X1 mouse button
        // => VK::MouseX2, // X2 mouse button
        11 => VK::Backspace, // BACKSPACE key
        12 => VK::Tab, // TAB key
        16 => VK::Enter, // ENTER key
        22 => VK::PauseBreak, // PAUSE key
        23 => VK::CapsLock, // CAPS LOCK key
        30 => VK::Escape, // ESC key
        35 => VK::Space, // SPACEBAR
        36 => VK::PageUp, // PAGE UP key
        37 => VK::PageDown, // PAGE DOWN key
        38 => VK::End, // END key
        39 => VK::Home, // HOME key
        40 => VK::ArrowLeft, // LEFT ARROW key
        41 => VK::ArrowUp, // UP ARROW key
        42 => VK::ArrowRight, // RIGHT ARROW key
        43 => VK::ArrowDown, // DOWN ARROW key
        47 => VK::PrintScreen, // PRINT SCREEN key
        48 => VK::Insert, // INS key
        49 => VK::Delete, // DEL key
        51 => VK::Alpha0, // 0 key
        52 => VK::Alpha1, // 1 key
        53 => VK::Alpha2, // 2 key
        54 => VK::Alpha3, // 3 key
        55 => VK::Alpha4, // 4 key
        56 => VK::Alpha5, // 5 key
        57 => VK::Alpha6, // 6 key
        58 => VK::Alpha7, // 7 key
        59 => VK::Alpha8, // 8 key
        60 => VK::Alpha9, // 9 key
        68 => VK::A, // A key
        69 => VK::B, // B key
        70 => VK::C, // C key
        71 => VK::D, // D key
        72 => VK::E, // E key
        73 => VK::F, // F key
        74 => VK::G, // G key
        75 => VK::H, // H key
        76 => VK::I, // I key
        77 => VK::J, // J Key
        78 => VK::K, // K Key
        79 => VK::L, // L Key
        80 => VK::M, // M Key
        81 => VK::N, // N Key
        82 => VK::O, // O Key
        83 => VK::P, // P Key
        84 => VK::Q, // Q Key
        85 => VK::R, // R Key
        86 => VK::S, // S Key
        87 => VK::T, // T Key
        88 => VK::U, // U Key
        89 => VK::V, // V Key
        90 => VK::W, // W Key
        91 => VK::X, // X Key
        92 => VK::Y, // Y Key
        93 => VK::Z, // Z Key
        94 => VK::Super, // Left Windows key (Natural keyboard)
        99 => VK::Keypad0, // Numeric keypad 0 key
        100 => VK::Keypad1, // Numeric keypad 1 key
        101 => VK::Keypad2, // Numeric keypad 2 key
        102 => VK::Keypad3, // Numeric keypad 3 key
        103 => VK::Keypad4, // Numeric keypad 4 key
        104 => VK::Keypad5, // Numeric keypad 5 key
        105 => VK::Keypad6, // Numeric keypad 6 key
        106 => VK::Keypad7, // Numeric keypad 7 key
        107 => VK::Keypad8, // Numeric keypad 8 key
        108 => VK::Keypad9, // Numeric keypad 9 key
        109 => VK::KeypadAsterisk, // Multiply key
        110 => VK::KeypadPlus, // Add key
        112 => VK::KeypadMinus, // Subtract key
        113 => VK::KeypadDelete, // Decimal key
        114 => VK::KeypadSlash, // Divide key
        115 => VK::F1, // F1 key
        116 => VK::F2, // F2 key
        117 => VK::F3, // F3 key
        118 => VK::F4, // F4 key
        119 => VK::F5, // F5 key
        120 => VK::F6, // F6 key
        121 => VK::F7, // F7 key
        122 => VK::F8, // F8 key
        123 => VK::F9, // F9 key
        124 => VK::F10, // F10 key
        125 => VK::F11, // F11 key
        126 => VK::F12, // F12 key
        // TODO: Add F13~F24
        // 127 => VK::F13, // F13 key
        // 128 => VK::F14, // F14 key
        // 129 => VK::F15, // F15 key
        // 130 => VK::F16, // F16 key
        // 131 => VK::F17, // F17 key
        // 132 => VK::F18, // F18 key
        // 133 => VK::F19, // F19 key
        // 134 => VK::F20, // F20 key
        // 135 => VK::F21, // F21 key
        // 136 => VK::F22, // F22 key
        // 137 => VK::F23, // F23 key
        // 138 => VK::F24, // F24 key
        147 => VK::NumLock, // NUM LOCK key
        148 => VK::ScrollLock, // SCROLL LOCK key
        163 => VK::LShift, // Left SHIFT key
        164 => VK::RShift, // Right SHIFT key
        165 => VK::LControl, // Left CONTROL key
        166 => VK::RControl, // Right CONTROL key
        167 => VK::LAlt, // Left ALT key
        168 => VK::RAlt, // Right ALT key
        189 => VK::Semicolon, // Used for miscellaneous characters; it can vary by keyboard. For the US standard keyboard, the ';:' key
        190 => VK::Equal, // For any country/region, the '+' key
        191 => VK::Comma, // For any country/region, the ',' key
        192 => VK::Minus, // For any country/region, the '-' key
        193 => VK::Dot, // For any country/region, the '.' key
        194 => VK::Slash, // Used for miscellaneous characters; it can vary by keyboard. For the US standard keyboard, the '/?' key
        195 => VK::Grave, // Used for miscellaneous characters; it can vary by keyboard. For the US standard keyboard, the '`~' key
        222 => VK::LeftBrace, // Used for miscellaneous characters; it can vary by keyboard. For the US standard keyboard, the '[{' key
        223 => VK::BackSlash, // Used for miscellaneous characters; it can vary by keyboard. For the US standard keyboard, the '\|' key
        224 => VK::RightBrace, // Used for miscellaneous characters; it can vary by keyboard. For the US standard keyboard, the ']}' key
        225 => VK::Apostrophe, // Used for miscellaneous characters; it can vary by keyboard. For the US standard keyboard, the 'single-quote/double-quote' key
        _ => VK::Other(code),
    }
}
