[package]
name = "skyhook"
version = "1.0.0"
edition = "2021"
license = "MIT"
description = "Global keyboard hooking"
readme = "README.md"
repository = "https://git.pikokr.dev/SkyHook/SkyHook"
build = "build.rs"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cancellation = "0.1.0"
chrono = "0.4.23"

[target.'cfg(target_os = "windows")'.dependencies]
winsafe = { version = "0.0.11", features = ["user", "kernel"] }

[target.'cfg(target_os = "linux")'.dependencies]
x11 = { version = "2.21.0", features = ["xlib", "xrecord"] }

[build-dependencies]
cc = "1.0.74"
swift-rs = { git = "https://github.com/pikokr/swift-rs.git", features = [
    "build",
] }
