[package]
name = "skyhook"
version = "0.1.0"
edition = "2021"

# [lib]
# name = "inputhook"
# crate-type = ["dylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cancellation = "0.1.0"

[target.'cfg(target_os = "windows")'.dependencies]
winsafe = { version = "0.0.11", features = ["user", "kernel"] }

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.24.1"
core-graphics = { version = "0.22.3", features = ["highsierra"] }
core-foundation = { version = "0.9.3" }
core-foundation-sys = { version = "0.8.3" }
lazy_static = "1.4.0"
