[package]
name = "skyhook"
version = "1.0.0"
edition = "2021"
license = "MIT"
description = "Global keyboard hooking"
readme = "README.md"
repository = "https://git.pikokr.dev/SkyHook/SkyHook"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cancellation = "0.1.0"

[target.'cfg(target_os = "windows")'.dependencies]
winsafe = { version = "0.0.11", features = ["user", "kernel"] }

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.24.1"
core-graphics = { version = "0.22.3", features = ["highsierra"] }
core-foundation = { version = "0.9.3" }
core-foundation-sys = { version = "0.8.3" }
lazy_static = "1.4.0"
