namespace SkyHook
{
    public enum SkyHookKeyCode : ushort
    {
        Escape,

        // Function Keys
        F1,
        F2,
        F3,
        F4,
        F5,
        F6,
        F7,
        F8,
        F9,
        F10,
        F11,
        F12,
        F13,
        F14,
        F15,
        F16,
        F17,
        F18,
        F19,
        F20,
        F21,
        F22,
        F23,
        F24,

        // 2nd Layer
        Grave,
        Alpha1,
        Alpha2,
        Alpha3,
        Alpha4,
        Alpha5,
        Alpha6,
        Alpha7,
        Alpha8,
        Alpha9,
        Alpha0,
        Minus,
        Equal,
        Backspace,

        // 3rd Layer
        Tab,
        Q,
        W,
        E,
        R,
        T,
        Y,
        U,
        I,
        O,
        P,
        LeftBrace,
        RightBrace,
        BackSlash,

        // 4th Layer
        CapsLock,
        A,
        S,
        D,
        F,
        G,
        H,
        J,
        K,
        L,
        Semicolon,
        Apostrophe,
        Enter,

        // 5th Layer
        LShift,
        Z,
        X,
        C,
        V,
        B,
        N,
        M,
        Comma,
        Dot,
        Slash,
        RShift,

        // 6th Layer
        LControl,
        LMeta,
        RMeta,
        LAlt,
        Space,
        RAlt,
        RControl,

        // Controls
        PrintScreen,
        ScrollLock,
        Pause,
        Insert,
        Home,
        PageUp,
        Delete,
        End,
        PageDown,
        ArrowUp,
        ArrowLeft,
        ArrowDown,
        ArrowRight,

        // Keypad
        NumLock,
        NumPad1,
        NumPad2,
        NumPad3,
        NumPad4,
        NumPad5,
        NumPad6,
        NumPad7,
        NumPad8,
        NumPad9,
        NumPad0,
        NumPadDivide,
        NumPadMultiply,
        NumPadSubtract,
        NumPadDecimal,
        NumPadAdd,
        NumPadEnter,

        // Mouse
        MouseLeft,
        MouseRight,
        MouseMiddle,
        MouseX1,
        MouseX2,

        // Uncategorized
        Unknown,
    }
}